common:
  env: produce  # 可选值: develop, test, produce (内网本地服, 外网测试服, 正式服)
  port: 8082
  log:
    #Debug、Info、Warn、Error、Fatal、Panic
    logLevel: 'Debug'
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  mongodb:
    timeout: 10
    database: "app"
    connection_string: "mongodb://localhost:27017"
  has_robot: true
  stopGame: false
